name: openconnect-vpn # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '8.08' # just for humans, typically '1.2+git' or '1.3.2'
summary: OpenConnect VPN Client # 79 char long summary
description: |
  OpenConnect is an SSL VPN client initially created to support Cisco's AnyConnect SSL VPN. It has since been ported to support the Juniper SSL VPN (which is now known as Pulse Connect Secure), and the Palo Alto Networks GlobalProtect SSL VPN.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  stoken:
    build-packages:
      - libtomcrypt-dev
      - libxml2-dev
      - autoconf
      - automake
      - libtool
      - build-essential
    source: https://github.com/cernekee/stoken/archive/v0.92.tar.gz
    plugin: make
    stage-packages:
      - libtomcrypt1
    override-pull: |
      snapcraftctl pull
      ./autogen.sh
      ./configure
  openconnect:
    build-packages:
      - build-essential
      - libp11-kit-dev
      - libp11-dev
      - autotools-dev
      - automake
      - libtool
      - gettext
      - vpnc-scripts
      - libxml2-dev
      - zlib1g-dev
      - libssl-dev
      - pkg-config
    source: ftp://ftp.infradead.org/pub/openconnect/openconnect-8.08.tar.gz
    # See 'snapcraft plugins'
    plugin: make
    stage-packages:
      - p11-kit
      - libp11-3
      - libxml2
      - libicu60
      - vpnc-scripts
      - libatm1
    override-pull: |
      snapcraftctl pull
      ./configure

apps:
  openconnect:
    command: usr/local/sbin/openconnect --script /snap/openconnect/current/usr/share/vpnc-scripts/vpnc-script
    adapter: full
    plugs:
      - network
      - network-observe
      - network-control



